# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Commet < Formula
  desc "Generate commit messages using an LLM"
  homepage "https://github.com/gcascio/homebrew-commet"
  version "0.0.1"

  on_macos do
    on_intel do
      url "https://github.com/gcascio/commet/releases/download/v0.0.1/commet_Darwin_x86_64.tar.gz"
      sha256 "2a0445906e84686f0424301172d3a0d2c53478adc678ff9e74b1896fe97e6ac0"

      def install
        bin.install "commet"
      end
    end
    on_arm do
      url "https://github.com/gcascio/commet/releases/download/v0.0.1/commet_Darwin_arm64.tar.gz"
      sha256 "4be348258afea55ef8d93cdd4c3f1dcb3bd9ca0649c668b071e651dc7d5ba724"

      def install
        bin.install "commet"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/gcascio/commet/releases/download/v0.0.1/commet_Linux_x86_64.tar.gz"
        sha256 "a5d57d9c57fbfd5b3809d1cf2cbdadab991db18636295dbae10d38812950da4b"

        def install
          bin.install "commet"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/gcascio/commet/releases/download/v0.0.1/commet_Linux_arm64.tar.gz"
        sha256 "0279d34be6130836b02d0c9e8a3d20e1948bdd775ff4c0dbd6ae5652b4e7120e"

        def install
          bin.install "commet"
        end
      end
    end
  end
end
